### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by 3fernandez**
## Overview

I think documentation is a gateway for potential users of the lib/project, and typos can cause misunderstanding of functionality for newcomers or even seasoned devs.

### CODE REVIEW

**Comment by bkuhlmann** [comment]
:bow: @3fernandez, good catch! Would you mind fixing the build so I can rebase your changes onto `master`? If you run the following on your feature branch, you'll see the build errors that need fixing:

``` 
bundle install
bundle exec rake
```

If you need help renaming your commits, let me know and I can help. BTW, feel free to squash both commits into once since they are related.

**Comment by 3fernandez** [comment]
Hey @bkuhlmann, first of all thanks for answer me, and I think I'll need your help.
I just updated the PR with requirements you've specified above, but it didn't update the checks.

Just to explain, my commit practices come from this post I've read a long time ago: https://chris.beams.io/posts/git-commit/

And lastly, I loved this rake task with code quality checks, I will try to implement in the project that I work. 😅

**Comment by bkuhlmann** [comment]
:bow: @3fernandez. Yeah, this project uses [Git Cop](https://github.com/bkuhlmann/git-cop) as a code quality check and linter for Git commits. Feel free to add it to your projects too. :tada: It uses a *Git Rebase Workflow*.

It looks like the last two commits were fixes to the original two commits when there should be only be one commit ultimately. This is easily fixable using `git rebase --interactive`. Once in the editor, I'd delete the last two commits and squash the second commit into the first while renaming it. That should resolve the conflict. Then when done rebasing, you can do a `git push --force-with-lease` and you'll be all set. :)

If that doesn't work, let me know and I can take over the feature branch and rework it for you while still giving you credit for the work performed.

**Comment by bkuhlmann** [comment]
Hey @3fernandez, wanted to check back and see how things are going on this? Would you like me to rebase this instead?

**Comment by 3fernandez** [comment]
Hey @bkuhlmann I just made the changes you've asked, can you check again if the PR is in shape to be merged?

Thanks for the help. 😆

**Comment by bkuhlmann** [comment]
@3fernandez, well, there is only one commit down but there should only be one file change. It looks like this modified one of my earlier commits which is causing a big diff on this PR. Would you mind if I modify and correct your changes so we can get this rebased on `master`?

**Comment by 3fernandez** [comment]
Hey @bkuhlmann, sure. And sorry for not completing what you asked for.

**Comment by bkuhlmann** [comment]
@3fernandez No worries. :) I've open up a new PR with the corrections you provide. Let me know if this looks good! In the meantime, I'll close this PR so we can focus on the other PR instead.

**Pull request closed without merging**
